# Generated by Django 3.2.8 on 2021-11-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
