version: "3.9"

services:
  app:
    build: .
    command: sh -c "python manage.py migrate && gunicorn config.wsgi -b 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    networks:
      - main
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - app
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - main

networks:
  main: